// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9YWwnWlPD46ub4BE6kJ2cL_sqKH1-kz0',
    appId: '1:292414120960:web:d180b6a778ab466d58e4e5',
    messagingSenderId: '292414120960',
    projectId: 'inventory-system-32a2',
    authDomain: 'inventory-system-32a2.firebaseapp.com',
    storageBucket: 'inventory-system-32a2.firebasestorage.app',
    measurementId: 'G-99KVBVEP39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1gQm8R5b9rPYI8-vdSnMrJoaLC7-c-PA',
    appId: '1:292414120960:android:a132cb5a61cf94a158e4e5',
    messagingSenderId: '292414120960',
    projectId: 'inventory-system-32a2',
    storageBucket: 'inventory-system-32a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJJOlW_CkfvvXJ_rkVAqUKn8H_G-Edcvs',
    appId: '1:292414120960:ios:9b702c322fbaf6ec58e4e5',
    messagingSenderId: '292414120960',
    projectId: 'inventory-system-32a2',
    storageBucket: 'inventory-system-32a2.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJJOlW_CkfvvXJ_rkVAqUKn8H_G-Edcvs',
    appId: '1:292414120960:ios:9b702c322fbaf6ec58e4e5',
    messagingSenderId: '292414120960',
    projectId: 'inventory-system-32a2',
    storageBucket: 'inventory-system-32a2.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9YWwnWlPD46ub4BE6kJ2cL_sqKH1-kz0',
    appId: '1:292414120960:web:526410448efff8ce58e4e5',
    messagingSenderId: '292414120960',
    projectId: 'inventory-system-32a2',
    authDomain: 'inventory-system-32a2.firebaseapp.com',
    storageBucket: 'inventory-system-32a2.firebasestorage.app',
    measurementId: 'G-B8PRS0M212',
  );
}
